# Generated by Django 5.1.7 on 2025-04-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_fornecedor_contato_fornecedor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
