# Generated by Django 5.2.4 on 2025-10-30 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('produtos', '0001_initial'),
        ('shared', '0002_rename_criado_em_cliente_data_criacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15)),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('documento_nfe', models.FileField(blank=True, null=True, upload_to='notas_fiscais/')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cliente')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fornecedor.fornecedor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='produtos.variacaoproduto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_anterior', models.DecimalField(decimal_places=4, max_digits=20)),
                ('quantidade_nova', models.DecimalField(decimal_places=4, max_digits=20)),
                ('tipo_operacao', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída'), ('Ajuste', 'Ajuste'), ('Lote Criado', 'Lote Criado'), ('Lote Excluído', 'Lote Excluído')], max_length=20)),
                ('motivo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='produtos.variacaoproduto')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico', to='movimentacao.lote')),
            ],
            options={
                'verbose_name': 'Histórico de Estoque',
                'verbose_name_plural': 'Históricos de Estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('entrada_saida', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cliente')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movimentacao.lote')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='produtos.variacaoproduto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimentacao.tipomovimentacao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
