# Generated by Django 5.1.7 on 2025-04-04 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0001_initial'),
        ('produtos', '0009_alter_produto_categoria_alter_produto_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='produto',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacao', to='produtos.produto'),
        ),
    ]
