# Generated by Django 5.2.4 on 2025-10-30 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('fornecedor', '0001_initial'),
        ('marcas', '0001_initial'),
        ('shared', '0002_rename_criado_em_cliente_data_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('data', 'Data'), ('bool', 'Booleano')], max_length=20)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_dinamicos', to='categorias.categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParametroEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=500)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('num_serie', models.CharField(blank=True, max_length=200, null=True)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='categorias.categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cliente')),
                ('fornecedor', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='fornecedor.fornecedor')),
                ('marca', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='marcas.marca')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoComposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cliente')),
                ('produto_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='produtos.produto')),
                ('produto_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='produtos.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sigla', models.CharField(max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fator_conversao', models.DecimalField(decimal_places=6, default=1, max_digits=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='produtos.produto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.unidademedida')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValorCampoDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=500)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.campodinamico')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_campos', to='produtos.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(blank=True, max_length=10, null=True)),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('estoque_minimo', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('codigo_barras', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='produtos.produto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.unidademedida')),
            ],
            options={
                'ordering': ['tamanho'],
            },
        ),
    ]
