# Generated by Django 5.1.7 on 2025-04-01 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_fornecedor_contato_fornecedor_email'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='fornecedor.fornecedor'),
            preserve_default=False,
        ),
    ]
