# Generated by Django 5.1.7 on 2025-04-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
