# Generated by Django 5.1.7 on 2025-04-04 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_status'),
        ('fornecedor', '0003_fornecedor_status'),
        ('marcas', '0002_marca_status'),
        ('produtos', '0008_produto_estoque_minimo_alter_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='categorias.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='fornecedor.fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='marcas.marca'),
        ),
    ]
